# -*- coding: utf-8 -*-
# Generated by Django 1.10.dev20160307181939 on 2016-05-07 01:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='birthdate',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
