# -*- coding: utf-8 -*-
# Generated by Django 1.10.dev20160307181939 on 2016-05-07 22:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_members_birthdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='country',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='members',
            name='city',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='members',
            name='zip_code',
            field=models.CharField(default='', max_length=200),
        ),
    ]
