# -*- coding: utf-8 -*-
# Generated by Django 1.10.dev20160307181939 on 2016-05-07 23:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_auto_20160507_2217'),
    ]

    operations = [
        migrations.CreateModel(
            name='location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(default='', max_length=200)),
                ('city', models.CharField(default='', max_length=200)),
                ('zip_code', models.CharField(default='', max_length=200)),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=9)),
                ('member_id', models.IntegerField(default=0)),
                ('is_home', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='members',
            name='country',
        ),
        migrations.AlterField(
            model_name='members',
            name='city',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='members',
            name='zip_code',
            field=models.CharField(max_length=200),
        ),
    ]
