# -*- coding: utf-8 -*-
# Generated by Django 1.10.dev20160307181939 on 2016-05-07 23:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_auto_20160507_2314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='members',
            name='city',
        ),
        migrations.RemoveField(
            model_name='members',
            name='zip_code',
        ),
    ]
