# -*- coding: utf-8 -*-
# Generated by Django 1.10.dev20160307181939 on 2016-05-08 03:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_auto_20160507_2325'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='username',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
