# -*- coding: utf-8 -*-
# Generated by Django 1.10.dev20160307181939 on 2016-05-08 05:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_auto_20160508_0409'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='hash_id',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
