# -*- coding: utf-8 -*-
# Generated by Django 1.10.dev20160307181939 on 2016-05-25 05:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0010_members_facebook_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='skills',
            name='image_id',
            field=models.IntegerField(default=0),
        ),
    ]
